[package]
name = "rvm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.3.2"
nom = "7.1.0"
num-derive = "0.3.3"
num-traits = "0.2.14"
tracing = "0.1.29"
javacake = { path = "libs/rvm-bind" }
time = { version = "0.3.5", features = ["macros"] }
tracing-subscriber = { version = "0.3.7", features = ["time"] }

[workspace]
members = [
    "./libs/rvm-bind",
    "./libs/rvm-reader",
]
