name: Build

on:
  - push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: "! contains(toJSON(github.event.commits.*.message), '[ci skip]')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Install LLVM
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 14
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace
      - name: Test
        uses: actions-rs/cargo@v1
        if: success() || failure()
        with:
          command: test
          args: --workspace
      - name: Format
        uses: actions-rs/cargo@v1
        if: success() || failure()
        with:
          command: fmt
          args: --all -- --check
      - name: Clippy
        uses: actions-rs/cargo@v1
        if: success() || failure()
        with:
          command: clippy
          args: --workspace -- -D warnings
